[book]
authors = ["Artem Ivashko", "George Cristian"]
language = "en"
multilingual = false
src = "src"
title = "Rust Course"

[build]
build-dir = "docs"

[output.html]
mathjax-support = true
additional-css = ["rustviz_plugin/visualization.css"]
additional-js = ["rustviz_plugin/helpers.js"]

[output.html.playground]
editable = true
